import { PageHeader, KV, StatusBadge, TierLabel } from "@/components/ui";
import { getSourceDetail } from "@/lib/queries/sources";
import { activateSource, archiveSource } from "@/lib/actions/sources";
import { createSourceDocument } from "@/lib/actions/source-documents";
import { SubmitButton } from "@/components/submit-button";
import { redirect } from "next/navigation";

async function activateAction(formData:FormData) { "use server"; await activateSource(String(formData.get("source_id"))); }
async function archiveAction(formData:FormData) { "use server"; await archiveSource(String(formData.get("source_id"))); }
async function createDocumentAction(formData:FormData) { "use server"; await createSourceDocument({ source_id:String(formData.get("source_id")), title:String(formData.get("title")), url:String(formData.get("url")), publication_date:String(formData.get("publication_date") || "") || undefined, parsed_content:String(formData.get("parsed_content") || "") || undefined, internal_notes:String(formData.get("internal_notes") || "") || undefined }); }

export default async function SourceDetailPage({ params }:{ params:Promise<{id:string}> }) {
  const { id } = await params; const source = await getSourceDetail(id); if (!source) redirect('/app/sources');
  return <><PageHeader title={source.name} subtitle={`${source.jurisdiction ?? '-'} · ${source.entity_type ?? '-'} · created ${source.created_at.slice(0,10)}`} actions={<><StatusBadge value={source.status} /><TierLabel tier={source.source_tier} /></>} /><div className="hv-body hv-stack"><div className="hv-card"><div className="hv-card-pad"><KV label="Domain" value={source.domain ?? source.canonical_url ?? '-'} /><KV label="Description" value={source.description || '-'} /><KV label="Contact" value={`${source.contact_name ?? '-'} ${source.contact_org ? `· ${source.contact_org}` : ''}`} /><KV label="Internal notes" value={source.internal_notes || '-'} /></div></div><div className="hv-grid hv-grid-2"><form action={activateAction} className="hv-form-card hv-stack"><input type="hidden" name="source_id" value={source.id} /><div className="hv-card-title">Activate source</div><SubmitButton className="hv-btn-success">Activate</SubmitButton></form><form action={archiveAction} className="hv-form-card hv-stack"><input type="hidden" name="source_id" value={source.id} /><div className="hv-card-title">Archive source</div><SubmitButton className="hv-btn-danger">Archive</SubmitButton></form></div><div className="hv-card"><div className="hv-card-pad"><div className="hv-section-head"><div className="hv-section-title">Source documents</div></div><div className="hv-table-wrap"><table className="hv-table"><thead><tr><th>Title</th><th>Publication date</th><th>Status</th><th>URL</th></tr></thead><tbody>{source.documents.map((doc:any)=><tr key={doc.id}><td>{doc.title}</td><td>{doc.publication_date ?? '-'}</td><td><StatusBadge value={doc.status} /></td><td><a href={doc.url} target="_blank">{doc.url}</a></td></tr>)}</tbody></table></div></div></div><form action={createDocumentAction} className="hv-form-card hv-form-grid"><input type="hidden" name="source_id" value={source.id} /><div><label className="hv-label">Title</label><input name="title" required /></div><div><label className="hv-label">Publication date</label><input type="date" name="publication_date" /></div><div className="hv-field-full"><label className="hv-label">URL</label><input name="url" required /></div><div className="hv-field-full"><label className="hv-label">Parsed content</label><textarea name="parsed_content" /></div><div className="hv-field-full"><label className="hv-label">Internal notes</label><textarea name="internal_notes" /></div><div className="hv-field-full hv-right"><SubmitButton className="hv-btn-primary">Capture document</SubmitButton></div></form></div></>;
}
