import { PageHeader, ButtonLink, EmptyState } from "@/components/ui";
import { getDossiers } from "@/lib/queries/dossiers";
import { buildPublishPreview } from "@/lib/publish/validate";
import { publishDossier } from "@/lib/actions/dossiers";
import { SubmitButton } from "@/components/submit-button";

async function publishAction(formData:FormData) { "use server"; await publishDossier({ dossier_id:String(formData.get("dossier_id")), effective_at:String(formData.get("effective_at")) || undefined }); }

export default async function PublishPage({ searchParams }:{ searchParams:Promise<any> }) {
  const params = await searchParams; const dossiers = await getDossiers({}); const selectedId = params.dossier_id ?? dossiers[0]?.id; const preview = selectedId ? await buildPublishPreview(selectedId, params.effective_at) : null;
  return <><PageHeader title="Publish preview" subtitle="Validate dossier immutability, evidence gates and client-facing snapshot before publication" actions={<ButtonLink href="/app/dossiers" variant="ghost">Back to dossiers</ButtonLink>} /><div className="hv-body hv-stack"><form className="hv-form-card hv-form-grid" method="GET"><div><label className="hv-label">Dossier</label><select name="dossier_id" defaultValue={selectedId}>{dossiers.map((d:any)=><option value={d.id} key={d.id}>{d.title} · v{d.version_number}</option>)}</select></div><div><label className="hv-label">Effective at</label><input type="datetime-local" name="effective_at" defaultValue={(params.effective_at ?? new Date().toISOString().slice(0,16))} /></div><div className="hv-field-full hv-right"><button className="hv-btn hv-btn-ghost" type="submit">Refresh preview</button></div></form>{!preview ? <EmptyState label="No dossier found" /> : <><div className={preview.can_publish ? 'hv-success-note' : 'hv-danger-note'}><div className="hv-card-title">Publish verdict</div><div>{preview.can_publish ? 'Ready to publish. No blocking errors found.' : 'Blocked. Resolve errors before publication.'}</div><div className="hv-meta" style={{ marginTop: 6 }}>Signals: {preview.stats.signal_count} · Approved: {preview.stats.approved_signal_count} · Evidence: {preview.stats.human_evidence_count}/{preview.stats.evidence_count} human/total</div></div><div className="hv-grid hv-grid-2"><div className="hv-card"><div className="hv-card-pad"><div className="hv-section-title">Issues</div><div className="hv-stack">{preview.issues.length === 0 ? <div>No issues found.</div> : preview.issues.map((item:any, idx:number)=><div key={idx} className={item.severity === 'error' ? 'hv-danger-note' : 'hv-note'}><div className="hv-card-title">{item.severity} · {item.code}</div><div>{item.message}</div></div>)}</div></div></div><div className="hv-card"><div className="hv-card-pad"><div className="hv-section-title">Snapshot JSON</div><pre className="hv-pre">{JSON.stringify(preview.snapshot, null, 2)}</pre></div></div></div><form action={publishAction} className="hv-form-card hv-stack"><input type="hidden" name="dossier_id" value={preview.dossier_id} /><input type="hidden" name="effective_at" value={preview.effective_at} /><div className="hv-card-title">Publish dossier</div><div>This writes an immutable snapshot and generates a scoped JSON feed token. Internal notes are excluded from the published payload.</div><SubmitButton className={preview.can_publish ? 'hv-btn-primary' : 'hv-btn hv-btn-ghost'}>{preview.can_publish ? 'Publish dossier' : 'Preview blocked'}</SubmitButton></form></>}</div></>;
}
