import Link from "next/link";
export function PageHeader({ title, subtitle, actions }:{ title:string; subtitle?:string; actions?:React.ReactNode; }) { return <div className="hv-header"><div><h1 className="hv-page-title">{title}</h1>{subtitle ? <div className="hv-page-subtitle">{subtitle}</div> : null}</div>{actions ? <div className="hv-inline">{actions}</div> : null}</div>; }
export function StatCard({ label, value, hint }:{ label:string; value:string|number; hint?:string; }) { return <div className="hv-card"><div className="hv-card-pad"><div className="hv-card-title">{label}</div><div className="hv-stat-value">{value}</div>{hint ? <div className="hv-stat-delta">{hint}</div> : null}</div></div>; }
export function ButtonLink({ href, children, variant="ghost" }:{ href:string; children:React.ReactNode; variant?:"primary"|"ghost"|"danger"|"success"; }) { return <Link href={href} className={`hv-btn hv-btn-${variant}`}>{children}</Link>; }
export function StatusBadge({ value }:{ value:any }) { const safe = String(value ?? "unknown"); return <span className={`hv-badge status-${safe}`}>{safe}</span>; }
export function DataClassBadge({ value }:{ value:any }) { const safe = String(value ?? "unknown"); return <span className={`hv-badge class-${safe}`}>{safe}</span>; }
export function ConfidenceBadge({ value }:{ value:any }) { const safe = String(value ?? "unknown"); return <span className={`hv-badge confidence-${safe}`}>{safe}</span>; }
export function TierLabel({ tier }:{ tier:any }) { const safe = String(tier ?? "unknown"); const colors:any = { official_primary:"var(--green)", official_secondary:"var(--blue)", company_primary:"var(--gold)", trusted_secondary:"var(--amber)", media_secondary:"var(--text-secondary)", community_low_trust:"var(--red)" }; return <span><span className="hv-pill-dot" style={{ background: colors[safe] ?? "var(--text-muted)" }} />{safe}</span>; }
export function KV({ label, value }:{ label:string; value:React.ReactNode; }) { return <div className="hv-kv"><div className="hv-kv-key">{label}</div><div>{value}</div></div>; }
export function EmptyState({ label, hint }:{ label:string; hint?:string; }) { return <div className="hv-card"><div className="hv-empty"><div style={{ fontSize:16, color:"var(--text-secondary)", marginBottom:6 }}>{label}</div>{hint ? <div>{hint}</div> : null}</div></div>; }
