import { PageHeader, KV, StatusBadge, DataClassBadge, ConfidenceBadge, ButtonLink } from "@/components/ui";
import { getDossierDetail } from "@/lib/queries/dossiers";
import { revokePublishEvent, createDossierVersion } from "@/lib/actions/dossiers";
import { SubmitButton } from "@/components/submit-button";
import { redirect } from "next/navigation";

async function revokeAction(formData:FormData) { "use server"; await revokePublishEvent({ publish_event_id:String(formData.get("publish_event_id")), revoke_reason:String(formData.get("revoke_reason") || "Manual revoke") }); }
async function versionAction(formData:FormData) { "use server"; await createDossierVersion(String(formData.get("dossier_id"))); }

export default async function DossierDetailPage({ params }:{ params:Promise<{id:string}> }) {
  const { id } = await params; const dossier = await getDossierDetail(id); if (!dossier) redirect('/app/dossiers');
  return <><PageHeader title={dossier.title} subtitle={`${dossier.workspace_name ?? dossier.workspace_id} · v${dossier.version_number} · ${dossier.jurisdiction ?? '-'}`} actions={<><StatusBadge value={dossier.status} />{dossier.latest_api_token ? <span className="hv-code">{dossier.latest_api_token.slice(0,20)}…</span> : null}</>} /><div className="hv-body hv-stack"><div className="hv-card"><div className="hv-card-pad"><KV label="Summary" value={dossier.summary || '-'} /><KV label="Internal notes" value={dossier.internal_notes || '-'} /><KV label="Signals" value={<span className="hv-code">{dossier.signal_count}</span>} /></div></div><div className="hv-card"><div className="hv-card-pad"><div className="hv-section-head"><div className="hv-section-title">Dossier items</div><ButtonLink href={`/app/publish?dossier_id=${dossier.id}`} variant="ghost">Preview publish</ButtonLink></div><div className="hv-table-wrap"><table className="hv-table"><thead><tr><th>Signal</th><th>Class</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{dossier.items.map((item:any)=><tr key={item.id}><td><div className="hv-title-row">{item.signal_title}</div><div className="hv-meta">{item.signal_type ?? '-'} · {item.signal_jurisdiction ?? '-'}</div></td><td><DataClassBadge value={item.signal_data_class} /></td><td><ConfidenceBadge value={item.signal_confidence_level} /></td><td><StatusBadge value={item.signal_review_status} /></td></tr>)}</tbody></table></div></div></div><div className="hv-grid hv-grid-2"><form action={versionAction} className="hv-form-card hv-stack"><input type="hidden" name="dossier_id" value={dossier.id} /><div className="hv-card-title">Create new version</div><div>Use when a published dossier needs a new editable draft version.</div><SubmitButton className="hv-btn-primary">Create version</SubmitButton></form><form action={revokeAction} className="hv-form-card hv-stack"><div className="hv-card-title">Revoke latest publish event</div><select name="publish_event_id" defaultValue={dossier.publish_events[0]?.id}>{dossier.publish_events.map((event:any)=><option value={event.id} key={event.id}>{event.id} · {event.status}</option>)}</select><textarea name="revoke_reason" placeholder="Revoke reason" required /><SubmitButton className="hv-btn-danger">Revoke token</SubmitButton></form></div></div></>;
}
